### ISSUE TITLE
Models using NO_PARENT can't use setPos() 

### ISSUE THREAD

**Issue by Sconed** [TheOneTrueZandra/Figura#23] opened 2021-03-28 00:39 UTC
I have a cube under the NO_PARENT folder, and using `model.NO_PARENT.the.setPos{1, 2, 3}` for example, doesn't change it's position in the world. The only factor that changes it's position is the position field in blockbench.

![image](https://user-images.githubusercontent.com/29988852/112738775-43db3980-8f23-11eb-9986-bc02c9222b4f.png)

**Comment by TheOneTrueZandra** [comment] 2021-03-30 00:52
Unable to reproduce this on the latest version. Give me an update when 0.0.4 comes out?

**Comment by TheOneTrueZandra** [comment] 2021-03-30 14:58
You may have misunderstood this bug, actually.


All groups/parts operate in pixel coordinates, and the X and Y coordinates are inverted (so you `setPos({-x*16,-y*16,z*16})` to set the part to a world-space position). There's a helper function I added in the `vectors` api last night that does this for you, `vectors.partToWorld(pos)`

Closing this issue.

**Closed by TheOneTrueZandra** 2021-03-30 14:58 UTC
